const getSampleTypes = () => {
    return [
        "BiologicalSex",
        "BloodType",
        "DateOfBirth",
        "LatestWeight",
        "WeightSamples",
        "LatestHeight",
        "HeightSamples",
        "LatestBmi",
        "LatestBodyFatPercentage",
        "LatestLeanBodyMass",
        "StepCount",
        "Samples",
        "AnchoredWorkouts",
        "DailyStepCountSamples",
        "DistanceWalkingRunning",
        "DailyDistanceWalkingRunningSamples",
        "DistanceCycling",
        "DailyDistanceCyclingSamples",
        "FlightsClimbed",
        "DailyFlightsClimbedSamples",
        "EnergyConsumedSamples",
        "ProteinSamples",
        "Water",
        "HeartRateSamples",
        "RestingHeartRate",
        "WalkingHeartRateAverage",
        "ActiveEnergyBurned",
        "BasalEnergyBurned",
        "AppleExerciseTime",
        "AppleStandTime",
        "Vo2MaxSamples",
        "BodyTemperatureSamples",
        "BloodPressureSamples",
        "RespiratoryRateSamples",
        "HeartRateVariabilitySamples",
        "RestingHeartRateSamples",
        "BloodGlucoseSamples",
        "CarbohydratesSamples",
        "SleepSamples",
        "Info",
        "MindfulSession",
        "Workout",
        "AuthStatus",
        "LatestBloodAlcoholContent",
        "BloodAlcoholContentSamples",
        "DistanceSwimming",
        "DailyDistanceSwimmingSamples",
        "OxygenSaturationSamples",
    ] as Array<string>;
};

export default getSampleTypes;
