import AppleHealthKit from "react-native-health";
import { HealthPermission } from "react-native-health";

const getReadPermissions = () => {
    return [
        AppleHealthKit.Constants.Permissions.ActiveEnergyBurned,
        AppleHealthKit.Constants.Permissions.AppleExerciseTime,
        AppleHealthKit.Constants.Permissions.AppleStandTime,
        AppleHealthKit.Constants.Permissions.BasalEnergyBurned,
        AppleHealthKit.Constants.Permissions.BiologicalSex,
        AppleHealthKit.Constants.Permissions.BloodAlcoholContent,
        AppleHealthKit.Constants.Permissions.BloodGlucose,
        AppleHealthKit.Constants.Permissions.BloodPressureDiastolic,
        AppleHealthKit.Constants.Permissions.BloodPressureSystolic,
        AppleHealthKit.Constants.Permissions.BodyFatPercentage,
        AppleHealthKit.Constants.Permissions.BodyMass,
        AppleHealthKit.Constants.Permissions.BodyMassIndex,
        AppleHealthKit.Constants.Permissions.BodyTemperature,
        AppleHealthKit.Constants.Permissions.DateOfBirth,
        AppleHealthKit.Constants.Permissions.Biotin,
        AppleHealthKit.Constants.Permissions.Caffeine,
        AppleHealthKit.Constants.Permissions.Calcium,
        AppleHealthKit.Constants.Permissions.Carbohydrates,
        AppleHealthKit.Constants.Permissions.Chloride,
        AppleHealthKit.Constants.Permissions.Cholesterol,
        AppleHealthKit.Constants.Permissions.Copper,
        AppleHealthKit.Constants.Permissions.EnergyConsumed,
        AppleHealthKit.Constants.Permissions.FatMonounsaturated,
        AppleHealthKit.Constants.Permissions.FatPolyunsaturated,
        AppleHealthKit.Constants.Permissions.FatSaturated,
        AppleHealthKit.Constants.Permissions.FatTotal,
        AppleHealthKit.Constants.Permissions.Fiber,
        AppleHealthKit.Constants.Permissions.Folate,
        AppleHealthKit.Constants.Permissions.Iodine,
        AppleHealthKit.Constants.Permissions.Iron,
        AppleHealthKit.Constants.Permissions.Magnesium,
        AppleHealthKit.Constants.Permissions.Manganese,
        AppleHealthKit.Constants.Permissions.Molybdenum,
        AppleHealthKit.Constants.Permissions.Niacin,
        AppleHealthKit.Constants.Permissions.PantothenicAcid,
        AppleHealthKit.Constants.Permissions.Phosphorus,
        AppleHealthKit.Constants.Permissions.Potassium,
        AppleHealthKit.Constants.Permissions.Protein,
        AppleHealthKit.Constants.Permissions.Riboflavin,
        AppleHealthKit.Constants.Permissions.Selenium,
        AppleHealthKit.Constants.Permissions.Sodium,
        AppleHealthKit.Constants.Permissions.Sugar,
        AppleHealthKit.Constants.Permissions.Thiamin,
        AppleHealthKit.Constants.Permissions.VitaminA,
        AppleHealthKit.Constants.Permissions.VitaminB12,
        AppleHealthKit.Constants.Permissions.VitaminB6,
        AppleHealthKit.Constants.Permissions.VitaminC,
        AppleHealthKit.Constants.Permissions.VitaminD,
        AppleHealthKit.Constants.Permissions.VitaminE,
        AppleHealthKit.Constants.Permissions.VitaminK,
        AppleHealthKit.Constants.Permissions.Zinc,
        AppleHealthKit.Constants.Permissions.Water,
        AppleHealthKit.Constants.Permissions.DistanceCycling,
        AppleHealthKit.Constants.Permissions.DistanceWalkingRunning,
        AppleHealthKit.Constants.Permissions.FlightsClimbed,
        AppleHealthKit.Constants.Permissions.HeartRate,
        AppleHealthKit.Constants.Permissions.RestingHeartRate,
        AppleHealthKit.Constants.Permissions.HeartRateVariability,
        AppleHealthKit.Constants.Permissions.Height,
        AppleHealthKit.Constants.Permissions.LeanBodyMass,
        AppleHealthKit.Constants.Permissions.MindfulSession,
        AppleHealthKit.Constants.Permissions.NikeFuel,
        AppleHealthKit.Constants.Permissions.RespiratoryRate,
        AppleHealthKit.Constants.Permissions.SleepAnalysis,
        AppleHealthKit.Constants.Permissions.StepCount,
        AppleHealthKit.Constants.Permissions.Steps,
        AppleHealthKit.Constants.Permissions.Vo2Max,
        AppleHealthKit.Constants.Permissions.Weight,
        AppleHealthKit.Constants.Permissions.Workout,
    ] as Array<HealthPermission>;
};

export default getReadPermissions;
